.PHONY: clean All

All:
	@echo "----------Building project:[ Trial - Debug ]----------"
	@cd "Trial" && "$(MAKE)" -f  "Trial.mk"
clean:
	@echo "----------Cleaning project:[ Trial - Debug ]----------"
	@cd "Trial" && "$(MAKE)" -f  "Trial.mk" clean
