.PHONY: clean All

All:
	@echo "----------Building project:[ COS201Project1 - Debug ]----------"
	@cd "COS201Project1" && "$(MAKE)" -f  "COS201Project1.mk"
clean:
	@echo "----------Cleaning project:[ COS201Project1 - Debug ]----------"
	@cd "COS201Project1" && "$(MAKE)" -f  "COS201Project1.mk" clean
