.PHONY: clean All

All:
	@echo "----------Building project:[ Project6 - Debug ]----------"
	@cd "Project6" && "$(MAKE)" -f  "Project6.mk"
clean:
	@echo "----------Cleaning project:[ Project6 - Debug ]----------"
	@cd "Project6" && "$(MAKE)" -f  "Project6.mk" clean
